# Database

## Purpose

This document describes the database structure supporting the ERP Vendor Payment Integration process.

The database model represents the business data required for the integration, as well as the technical records used to monitor integration execution and errors.

This model represents only the relevant data scope for the integration and does not represent the complete production database.

---

## Entity Relationship Diagram

The following ERD illustrates the relationships between the business entities involved in the Payment Acquisition process.

![Entity Relationship Diagram](../diagrams/erd.png)

**Figure 1. Entity Relationship Diagram**

---

## Relationships

### Vendor → Contract

- One Vendor can have multiple Contracts.
- Each Contract belongs to one Vendor.

**Relationship:** `Vendor 1 : N Contract`

### Vendor → Invoice

- One Vendor can have multiple Invoices.
- Each Invoice belongs to one Vendor.

**Relationship:** `Vendor 1 : N Invoice`

### Contract → Invoice

- One Contract can have multiple Invoices.
- Each Invoice belongs to one Contract.

**Relationship:** `Contract 1 : N Invoice`

### Invoice → Approval Document

- One Invoice can have one Approval Document.
- Each Approval Document belongs to one Invoice.

**Relationship:** `Invoice 1 : 1 Approval Document`

---

## Relationships Summary

| Parent Entity | Child Entity | Relationship |
|---|---|---|
| Vendor | Contract | 1 : N |
| Vendor | Invoice | 1 : N |
| Contract | Invoice | 1 : N |
| Invoice | Approval Document | 1 : 1 |

The Integration Log and Error Log have no foreign-key relationships to the business entities because they serve as independent technical records of integration activity.

---

## Tables

### 1. Vendor

Stores vendor information required by the Payment Acquisition process.

| Column | Data Type | Key | Description |
|---|---|---|---|
| `vendor_id` | VARCHAR(20) | PK | Unique vendor identifier |
| `vendor_name` | VARCHAR(100) | | Registered vendor name |
| `tax_number` | VARCHAR(30) | | Vendor tax identification number |

---

### 2. Contract

Stores contract information associated with a vendor.

| Column | Data Type | Key | Description |
|---|---|---|---|
| `contract_number` | VARCHAR(50) | PK | Unique contract identifier |
| `vendor_id` | VARCHAR(20) | FK | Vendor associated with the contract |
| `work_description` | VARCHAR(500) | | Description of contracted work |

---

### 3. Invoice

Stores invoice information associated with the vendor and contract.

| Column | Data Type | Key | Description |
|---|---|---|---|
| `invoice_id` | VARCHAR(50) | PK | Unique invoice identifier |
| `vendor_id` | VARCHAR(20) | FK | Vendor associated with the invoice |
| `contract_number` | VARCHAR(50) | FK | Contract associated with the invoice |
| `invoice_amount` | DECIMAL(18,2) | | Invoice amount |
| `invoice_date` | DATE | | Invoice issue date |
| `currency` | CHAR(3) | | ISO 4217 currency code |

---

### 4. Approval Document

Stores the digitally signed payment approval document generated by the Finance Portal.

| Column | Data Type | Key | Description |
|---|---|---|---|
| `approval_document_id` | VARCHAR(50) | PK | Unique approval document identifier |
| `invoice_id` | VARCHAR(50) | FK | Invoice associated with the approval |
| `approval_document` | BLOB | | Digitally signed PDF document |
| `approval_document_url` | VARCHAR(500) | | Document reference or access URL |
| `approval_date` | DATETIME | | Date and time of approval |

---

### 5. Integration Log

Records the technical execution of integration operations.

The Integration Log is intentionally independent from the business entities. Its purpose is to provide a technical record of integration activity rather than represent business relationships.

| Column | Data Type | Key | Description |
|---|---|---|---|
| `log_id` | BIGINT | PK | Unique integration log identifier |
| `log_status` | VARCHAR(20) | | Result of the integration operation |
| `log_date` | DATE | | Date of the integration event |
| `log_time` | TIME | | Time of the integration event |
| `operation` | VARCHAR(50) | | Integration operation performed |
| `source_system` | VARCHAR(50) | | System initiating the interaction |
| `target_system` | VARCHAR(50) | | System receiving the interaction |

---

### 6. Error Log

Records errors encountered during integration processing.

The Error Log is maintained independently from the business entities and Integration Log to provide a dedicated record of integration failures.

| Column | Data Type | Key | Description |
|---|---|---|---|
| `log_id` | BIGINT | PK | Unique error log identifier |
| `error_type` | VARCHAR(50) | | Category of integration error |
| `reason` | VARCHAR(500) | | Description of the error |
| `error_log_time` | DATETIME | | Date and time the error occurred |

---

## Key Design Considerations

### Primary Keys

Each business entity has a unique primary key to identify individual records.

### Foreign Keys

Foreign keys establish relationships between Vendor, Contract, Invoice, and Approval Document while maintaining referential integrity.

### Data Integrity

Required fields and appropriate data types are used to ensure that business data is stored consistently.

### Document Storage

The signed approval document is stored as binary data using a `BLOB` field. The document is expected to be a digitally signed PDF.

### Integration Logging

Integration activity is recorded independently using the Integration Log. Each record identifies the operation, source system, target system, execution status, and timestamp.

### Error Logging

Integration failures are recorded separately in the Error Log to support troubleshooting and operational monitoring.
